version: '3'

services:
  db:
    # this is the connection in pgadmin when you are using the docker-compose
    container_name: postgres_db
    image: postgres:15.1
    restart: always

    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=monolith-db

  pgAdmin:
    user: root
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123123
      - PGADMIN_DEFAULT_EMAIL=user@gmail.com
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json
  monolith:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
    container_name: monolith-be
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:123123@db:5432/monolith-db
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./be/src
    #       target: /app/src
    #       ignore:
    #         - node_modules/
    #     - action: rebuild
    #       path: package.json

volumes:
  postgres-db:
    external: false
