
### Update user name

PATCH http://localhost:3000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoSWQiOiJmYTZjZTFmNy04MTlkLTRkZmQtYWIxOS1lNGFiZmE0NzkxNzUiLCJpYXQiOjE3Mzg4NDgzNDN9.kVo1O_dx0s6m4ZstTDVWI_O929xUs60d0AWxsXf-qsQ
Content-Type: application/json

{
    "name": "changed_name_fixed"
}

### Get all users, only ADMIN can do it
GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoSWQiOiJmYTZjZTFmNy04MTlkLTRkZmQtYWIxOS1lNGFiZmE0NzkxNzUiLCJpYXQiOjE3Mzg4NDgzNDN9.kVo1O_dx0s6m4ZstTDVWI_O929xUs60d0AWxsXf-qsQ